version: '3'
services:
  student_service:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
    ports:
      - "8080:8080"

  mongo:
    restart: unless-stopped
    image: mongo:4
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "curl", "-f", "mongodb://localhost:27017"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s
