name: Build, Test, and Push
on: [push]
env:
  IMAGE_NAME: student_service
  REPO_NAME: jkasikci/student_service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build docker image
      run: |
        docker build . -t $REPO_NAME/$IMAGE_NAME

    - name: Set up Docker Compose
      run: |
        sudo apt-get install docker-compose

    - name: Run docker-compose
      run: |
        docker-compose up -d
        sleep 30

    - name: "Check files existence"
      uses: andstor/file-existence-action@v2
      with:
        files: "postman/collection.json,postman/environment.json"
        fail: true

    - name: Run API Tests
      id: run-newman
      uses: anthonyvscode/newman-action@master
      with:
        collection: postman/collection.json
        environment: postman/environment.json
        reporters: cli
        bail: true

    - name: Check if we failed
      id: fail-check
      shell: bash
      env:
        JSON_DOC: ${{ steps.run-newman.outputs.summary }}
      run: |
        printf '%s\n' "$JSON_DOC" > summary.json
        cat summary.json
        if grep -q Collection summary.json; then
          echo "failed=false" >> $GITHUB_OUTPUT;
        else
          echo "failed=true" >> $GITHUB_OUTPUT;
        fi

    - name: fail if empty
      if: ${{ steps.fail-check.outputs.failed == 'true' }}
      run: exit 1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push image to Docker Hub
      run: |
        docker push $REPO_NAME/$IMAGE_NAME

    - name: Stop containers
      run: |
        docker-compose down
