name: Build, Test, and Push

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: student_service
  REPO_NAME: jkasikci/student_service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build . -t $REPO_NAME/$IMAGE_NAME

      - name: Run MongoDB container
        run: |
          docker network create my_network
          docker run -d --name mongodb --network my_network -p 27017:27017 mongo:latest

      - name: Run student service container
        run: |
          docker run -d --name student_service --network my_network -p 8080:8080 $REPO_NAME/$IMAGE_NAME:latest

      - name: Check files existence
        uses: andstor/file-existence-action@v2
        with:
          files: "postman/collection.json,postman/environment.json"
          fail: true

      - name: Run API tests
        id: run-newman
        uses: anthonyvscode/newman-action@master
        with:
          collection: postman/collection.json
          environment: postman/environment.json
          reporters: cli
          bail: true

      - name: Check if we failed
        id: fail-check
        shell: bash
        env:
          JSON_DOC: ${{ steps.run-newman.outputs.summary }}
        run: |
          printf '%s\n' "$JSON_DOC" > summary.json
          cat summary.json
          if grep -q Collection summary.json; then
            echo "failed=false" >> $GITHUB_OUTPUT;
          else
            echo "failed=true" >> $GITHUB_OUTPUT;
          fi

      - name: Fail if empty
        if: ${{ steps.fail-check.outputs.failed == 'true' }}
        run: exit 1

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push image to Docker Hub
        run: |
          docker push $REPO_NAME/$IMAGE_NAME